name: Lint

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  azlint:
    name: AZLint
    runs-on: ubuntu-latest
    container:
      image: matejkosiarcik/azlint:0.6.11
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files

      - name: Run AZLint
        run: |
          if [ "$GITHUB_REF_NAME" = main ]; then
            azlint
          else
            azlint # --only-changed # TODO: Fix
          fi

  mega-linter:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v7.11.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          DEFAULT_BRANCH: main
          MEGALINTER_CONFIG: .config/.mega-linter.yml

  super-linter:
    name: SuperLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files

      - name: Run SuperLinter
        uses: super-linter/super-linter@v6.4.1
        env:
          # global settings
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: .config/
          MULTI_STATUS: false

          # disable
          VALIDATE_BASH_EXEC: false
          VALIDATE_CSS: false
          VALIDATE_JSON: false # Because eslint considers .json as .js (so rules like single-quote don't make sense)
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_NATURAL_LANGUAGE: false # TODO: Enable
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_RUST_2015: false
          VALIDATE_RUST_CLIPPY: false # Somehow fails the compilation
          VALIDATE_DOCKERFILE_HADOLINT: false # Incorrectly tries to lint .dockerfilelintrc

          # config files
          DOCKERFILE_HADOLINT_FILE_NAME: .hadolint.yaml
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_FLAKE8_CONFIG_FILE: setup.cfg
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          PYTHON_PYLINT_CONFIG_FILE: pyproject.toml
          RUBY_CONFIG_FILE: .rubocop.yml
          YAML_CONFIG_FILE: .yamllint.yml
