name: Lint

on:
  pull_request:

jobs:
  mega-linter:
    name: Mega-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files

      - name: Mega Linter
        uses: nvuillam/mega-linter@v6.22.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          DEFAULT_BRANCH: main
          MEGALINTER_CONFIG: .config/.mega-linter.yml
